### ISSUE TITLE
Update to new HTTP client API from Micronaut 2

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-netflix#15]
See https://github.com/micronaut-projects/micronaut-netflix/pull/14/checks?check_run_id=646662711

**Comment by alvarosanchez** [comment]
Why was this closed?

**Comment by ilopmar** [comment]
The log there wasn't available anymore and I've assumed it was something that make some test fail. As there were no test failures I've closed it.

**Comment by alvarosanchez** [comment]
Actually, there were failing tests.

But if all tests are now passing with Micronaut 2, I guess it can be closed.
